### ISSUE TITLE
가입 로직 변경

### ISSUE THREAD

**Issue by nearKim** [nearKim/Caffein2#12]
변경 전:
1. 회원 정보 입력
2. 이메일 검증
3. 가입 설문 작성
-로그인 가능- 
4. 어디어디로 돈내세요~ 페이지 보여줌
5. 운영진의 입금 확인

변경 후:
1. 회원 정보 입력
2. 이메일 검증
3. 가입 설문 작성
4. 어디어디로 돈내세요~페이지 보여줌
5. 운영진의 입금 확인
-로그인 가능- 

이렇게 바꾸면 어떨까
- 기존 방식대로라면 Permission을 다루기가 어려워짐. 똑같이 로그인 한 유져인데 돈을 낸 사람은 댓글이나 포스팅을 볼 수 없어야 하고 돈낸 사람은 볼 수 있어야 하니까 사용자 정의 permission을 새로 짜야 함.
- 돈내기전엔 가입 완료된게 아니니까 아예 로그인을 못하게 막아버리는 것이 나을 수도 있을듯.

**Comment by nearKim** [comment]
변경 확정

**Comment by KwangdeokPark** [comment]
로그인 하지 않아도 신입회원 가입 설문에 접근가능.
