### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by nearKim** [nearKim/Caffein2#16]
1. - [x] 네이버지도 <strike>/ 구글맵 </strike>통합(half done)

 
2. - [x] Template 변경 및 디자인 회의

3. - [x] Admin page

4. App 추가생성

    - [x] Cafe

    - [x] PhotoAlbum

5. - [x] Auth, Permission 검토

6. - [x] Meetings View/Template 정교화

7. - [ ] Like 버튼

8. - [x] core 앱 리팩터

9. - [x] JS / AJAX 기본적 적용(종속적 드롭다운 등)

10. - [ ] AWS 및 지불정보 정리

11. - [x] Coffeemeeting 및 Cafe 앱 사용모델 생성

12. - [x] 디자이너 협업을 위한 알파 배포 

13. - [x] 짝지모임 참여자 검색하여 짝지 점수 올리기(참여 버튼에서 더하고 빼고 해야할듯) 

14. - [x] 학기 종료 후 짝지 점수 상향 안되게 처리

15. - [x] 댓글창에서 *내용 없애기

17. - [x] 짝모 정말 인스타그램처럼 화살표 클릭하면 다음사진 나오게 할 수 있을까

18. - [x] 커피교육, 공식모임 등에서 사진 업로드시 크기 조정 필요 => 디자이너 협의 후 진행

19. - [x] 커모 페이지에서 카페이름을 누르면 카페 디테일 페이지로 들어가게 하자.
    16. - [ ] 부트스트랩 그냥 cdn으로 통합하자

------------1차 릴리즈(~8월)
12. REST API 
13. React integration
-------------2차 릴리즈(~9월)

**Comment by nearKim** [comment]
공식모임, 커피교육 view및 template 정교화

**Comment by nearKim** [comment]
like버튼

**Comment by nearKim** [comment]
추가사항
1. 짝모 list는 현재 학기만 보이도록 설정해야 하는가?

**Comment by nearKim** [comment]
Cafe 앱 관련
1. - [ ] Cafe Detail 페이지 예쁘게
2. - [ ] Cafe 등록 후 '여기서 커모열기 버튼 추가
3. - [ ] Cafe 등록 후 수정은 회원이 가능 / 삭제는 운영진만 가능
4. - [ ] 회원들의 Cafe 코멘트도 나중에 추가하자. 그래야 App 포팅할때 좋겠지

**Comment by KwangdeokPark** [comment]
Photo Album 앱 관련
1. - [ ] clear database는 운영진과 앨범 uploader만 가능
2. - [ ] 모든 유저가 앨범에 photo를 업로드 가능하지만, 지울 수 있는 사진은 본인이 올린 사진뿐
3. - [ ] 기타 디지인. 특히 앨범 create하는 부분과, edit하는 부분 디자인 개선 필요

**Comment by nearKim** [comment]
사진 크기 조정 이슈
1. 짝모 사진
2. 커모 생성 사진
3. 커교 생성 사진
4. 공식모임 생성 사진
