### ISSUE TITLE
survey에서 가입기간임에도 가입기간이 아니라고 뜸

### ISSUE THREAD

**Issue by nearKim** [nearKim/Caffein2#18]
버그 발생상황:
 운영정보
<img width="431" alt="2018-08-19 1 49 36" src="https://user-images.githubusercontent.com/30017143/44305618-c805d180-a3b6-11e8-93e1-90fe14118517.png">

이 상황에서 8월 18일 기준으로 신규회원가입 정보를 모두 입력하고, 인증메일이 받은 후 메일에 담긴 활성화 코드를 따라가면 다음과 같은 화면이 뜸.
<img width="621" alt="2018-08-19 1 51 04" src="https://user-images.githubusercontent.com/30017143/44305624-ee2b7180-a3b6-11e8-8b43-a0827c08188a.png">

운영정보 받아오는 survey앱의 로직쪽 검토 필요

**Comment by KwangdeokPark** [comment]
수정 완료
