### ISSUE TITLE
[Bug] photo_album의 모델이 s3 boto와 연동되지 않는 이슈

### ISSUE THREAD

**Issue by nearKim** [nearKim/Caffein2#40]
AWS S3를 사용하기 위해서 django의 커넥터인 boto 라이브러리를 사용해야 한다. 그런데 어떠한 이유인지는 모르겠으나 photo_album의 모델이 boto와 호환되지 않는듯 하다. Heroku의 Sentry log는 다음과 같다.

<img width="1116" alt="2018-09-26 11 38 46" src="https://user-images.githubusercontent.com/30017143/46054236-61c45980-c181-11e8-98f0-3bdf0acfcd66.png">
<img width="1107" alt="2018-09-26 11 39 01" src="https://user-images.githubusercontent.com/30017143/46054243-65f07700-c181-11e8-8430-53d05b0aa2da.png">
<img width="1078" alt="2018-09-26 11 39 11" src="https://user-images.githubusercontent.com/30017143/46054246-68eb6780-c181-11e8-83b0-a3dc0fb756d5.png">

**Comment by KwangdeokPark** [comment]
thumbnail field를 없애고, path나 save함수에 django.core.files.storage의 default_storage함수를 이용해 버그 해결
