### ISSUE TITLE
[TODOs] update

### ISSUE THREAD

**Issue by nearKim** [nearKim/Caffein2#55]
- [x]  1. 사진첩 리팩터

- [x]  짝모에서 paginator 추가!!!!

- [x] 2. 회원들 비밀번호 변경 가능하게 수정
- [x] 3. 신입회원 가입 메일에서 html 렌더링 문제
  - [x] 3.1. site_id fixture 검토
- [x] 4. 커모 결과 짝모와 통합
  - [x] 4.1. 카페인 피드(feed)로 통합
  - [x] 4.2. 새로운 모델생성 검토
- [ ] 5. Facebook API 확정
- [x] 6. Heroku main index page 성능 검토
- [ ] 7. Like 버튼 
- [ ] 8. 알림 기능
- [ ] 9. 내가 연 커모

**Comment by nearKim** [comment]
작업순서: 1-2-3-4-5-배포-6검토-7

**Comment by KwangdeokPark** [comment]
3.
<img width="516" alt="2018-10-09 01 29 58" src="https://user-images.githubusercontent.com/37106255/46621673-0d4ab200-cb63-11e8-88a3-a0537b5999cc.png">
html 테그를 지워줘서 해결 필요

**Comment by nearKim** [comment]
새 enhancement로 통합
