### ISSUE TITLE
[Bug] cafes listview가 제대로 작동하지 않는 문제

### ISSUE THREAD

**Issue by KwangdeokPark** [nearKim/Caffein2#58]
<img width="811" alt="2018-10-03 23 43 40" src="https://user-images.githubusercontent.com/37106255/46447704-665ec280-c7be-11e8-8f0c-d99f0867cc31.png">

localhost:8000/cafes/ 에 해당하는 뷰가 제대로 작동하지 않는다.

**Comment by nearKim** [comment]
querystring없이 url로 직접접근하여 발생하는 문제. 버그아님. 이렇게 접근하는 사용자가 존재할 가능성이 있으므로 예외처리는 해야함.
